#pragma once

#define MAIN_Version "d8ffa49"
#define KNX_Version "2.3.1+7124a64"
#define MODULE_ClimateControl_Version "0.1.0+41e466c"
#define MODULE_ClimateControl_Version_Major 0
#define MODULE_ClimateControl_Version_Minor 1
#define MODULE_ClimateControl_Version_Revision 0
#define MODULE_ClimateControl_ETS 1
#define MODULE_Common_Version "1.8.1+f6dbb3c"
#define MODULE_Common_Version_Major 1
#define MODULE_Common_Version_Minor 8
#define MODULE_Common_Version_Revision 1
#define MODULE_Common_ETS 24
#define MODULE_LogicModule_Version "4.3.0+8c0d835"
#define MODULE_LogicModule_Version_Major 4
#define MODULE_LogicModule_Version_Minor 3
#define MODULE_LogicModule_Version_Revision 0
#define MODULE_LogicModule_ETS 67
#define MODULE_FileTransferModule_Version "0.1.5+178f186"
#define MODULE_FileTransferModule_Version_Major 0
#define MODULE_FileTransferModule_Version_Minor 1
#define MODULE_FileTransferModule_Version_Revision 5
#define MODULE_FileTransferModule_ETS 1
#define MODULE_HeatingActuator_Version "0.1.0+5c4e8fe"
#define MODULE_HeatingActuator_Version_Major 0
#define MODULE_HeatingActuator_Version_Minor 1
#define MODULE_HeatingActuator_Version_Revision 0
#define MODULE_HeatingActuator_ETS 1
#define MODULE_OneWireModule_Version "2.2.0+cbd02c5"
#define MODULE_OneWireModule_Version_Major 2
#define MODULE_OneWireModule_Version_Minor 2
#define MODULE_OneWireModule_Version_Revision 0
#define MODULE_OneWireModule_ETS 34
#define MODULE_SensorDevices_Version "4.1.1+369412c"
#define MODULE_SensorDevices_Version_Major 4
#define MODULE_SensorDevices_Version_Minor 1
#define MODULE_SensorDevices_Version_Revision 1
#define MODULE_SensorDevices_ETS 65
